version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: dockerdb
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    container_name: junior-crud-service
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: dockerpassword
    depends_on:
      - postgres

volumes:
  postgres-data:
